\" SPDX-License-Identifier: GFDL-1.3-no-invariants-or-later
\" SPDX-FileCopyrightText: Copyright © 2024 Intel Corporation.
\"
.TH CLKMGR_PROXY "8" "June 2025" "clkmgr_proxy"
.SH NAME
clkmgr_proxy \- Clock Manager proxy service
.SH DESCRIPTION
Usage of clkmgr_proxy:
Options:
.HP
\fB\-f\fR [file] Read configuration from 'file'
.HP
\fB\-a\fR <0|1> Open message queue in access all mode
.IP
0: disable(default), 1: enable
.HP
\fB\-l\fR <lvl> Set log level
.IP
0: ERROR, 1: INFO(default), 2: DEBUG, 3: TRACE
.HP
\fB\-q\fR <0|1> Enable or disable quiet mode
.IP
0: disable, 1: enable
.HP
\fB\-s\fR <0|1> Enable or disable use of system logging
.IP
0: disable, 1: enable
.TP
\fB\-v\fR
Show version
.TP
\fB\-h\fR
Show help message
