# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# Docker file for stage 1 of Gentoo container for building and installing
# Search packages at: https://packages.gentoo.org/
# emerge:
# https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html
# -t                        Shows the dependency tree
# -v                        Verbose mode
# --autounmask=y            Automatically unmask packages and generate package.use settings
# --autounmask-write=y      Changes are written to config file
# --autounmask-only=y       Skip package building
# --autounmask-backtrack=y  Allow backtracking after autounmask has detected
# --autounmask-continue=y   Automatically apply autounmask changes and continue to execute
# --onlydeps                Only merge (or pretend to merge) the dependencies
###############################################################################
FROM gentoo/stage3
LABEL org.opencontainers.image.authors="Erez Geva <ErezGeva2@gmail.com>"\
      org.opencontainers.image.description="Gentoo build for libptpmgmt"
ARG USER
RUN emerge-webrsync && emerge -tvuD @world &&\
    echo "CONFIG_PROTECT_MASK=/etc/portage" >> /etc/portage/make.conf &&\
    p='dev-lang/go app-portage/portage-utils app-shells/bash\
    app-admin/sudo app-admin/chrpath app-editors/vim app-misc/jq\
    app-text/discount app-text/doxygen sys-devel/m4\
    sys-apps/fakeroot sys-apps/which dev-build/libtool\
    dev-build/make dev-util/pkgconf dev-util/astyle dev-util/patchelf\
    dev-vcs/git dev-libs/criterion dev-cpp/gtest dev-debug/gdb\
    dev-lang/swig app-text/pandoc dev-lang/perl dev-lang/ruby dev-lang/python\
    dev-lang/lua dev-lua/luaposix dev-lang/php dev-lang/tcl sys-devel/gcc\
    dev-util/cppcheck media-gfx/graphviz perl-core/Test-Simple\
    app-text/texlive-core dev-texlive/texlive-fontutils net-misc/chrony\
    dev-util/quilt app-text/cmark dev-tcltk/tcllib dev-tcltk/tclx' &&\
    emerge -tv --autounmask=y --autounmask-write=y --autounmask-only=y\
    --autounmask-backtrack=y --autounmask-continue=y llvm-core/clang $p &&\
    emerge -tv $p && echo "$USER ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers &&\
    sed -i 's/^enable_dl\s*=\s*Off/enable_dl = On/' /etc/php/*/php.ini &&\
    mkdir -p /t0 && cd /t0 && git clone https://github.com/linux-rt/librtpi &&\
    cd librtpi && autoreconf -i &&\
    ./configure --prefix=/usr --includedir=/usr/include --libdir=/usr/lib64 &&\
    make install &&\
    cd /t0 && git clone https://github.com/mlichvar/libchrony &&\
    cd libchrony && make install includedir=/usr/include libdir=/usr/lib64 &&\
    cd && rm -Rf /t0
ARG UID COOKIE SRC DST
