# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# Docker file for stage 2 of Gentoo container for building and installing
###############################################################################
FROM portage.1
RUN emerge -tv llvm-core/clang
ARG UID USER COOKIE SRC DST
