# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# GitHub build stage 2 gentoo container image an upload it
###############################################################################

name: gentoo 2 build docker image

# Start manually and when step 1 is done
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["gentoo 1 build docker image"]
    types: [ completed ]
    branches: [ '*' ]

env:
  REGISTRY: ghcr.io

jobs:
  gentoo:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Sets permissions of the GITHUB_TOKEN to allow upload new container
    permissions:
      contents: read
      packages: write

    steps:

    - name: checkout repository
      uses: actions/checkout@v4

    - name: log in to the container registry
      if: ${{ github.actor == github.repository_owner }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      if: ${{ github.actor == github.repository_owner }}
      run: gentoo/make_docker.sh -b2 -tg -fg
